changed by Asadullokh && Ibrohim (support) #59 closed
NET-Bootcamp-N11/BookStore pull request #75
Opened 2024-03-18 09:48 UTC by Asadullokh27

#59 closed

2024-03-18 13:29 UTC, Tohirjon-Odilov requested changes

2024-03-18 13:29 UTC, Tohirjon-Odilov commented on src/BookStore.Presentation/MVC/Controllers/AuthorsController.cs
> +                goto res;
Goto'da foydalanish yaxshimas o'zilarga qarelar

2024-03-18 13:29 UTC, Tohirjon-Odilov commented on src/BookStore.Presentation/MVC/Controllers/AuthorsController.cs
> +                goto res;
Umuman yaxshi ish emas

2024-03-18 18:47 UTC, SardorSohinazarov commented on src/BookStore.Presentation/MVC/Controllers/AuthorsController.cs
> +                goto res;
+

2024-03-18 18:47 UTC, SardorSohinazarov commented on src/BookStore.Presentation/MVC/Controllers/AuthorsController.cs
> +                goto res;
Goto ni almashtirish kerak

2024-03-19 03:14 UTC, Asadullokh27 commented on src/BookStore.Presentation/MVC/Controllers/AuthorsController.cs
> +                goto res;
Hop boladi ustoz!

2024-03-19 03:23 UTC, merged